
name: buildAndPushToGcr

on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build-and-push-gcr:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: fronendreact
      PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
      GIT_TAG: latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: tomganemo1987/docker101tutorial:frontend-react

      - uses: google-github-actions/auth@v0.4.0 #https://github.com/google-github-actions/auth
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: Push Docker Image to Container Registry (GCR)
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
